/*
 * jQuery throttle / debounce - v1.1 - 3/7/2010
 * http://benalman.com/projects/jquery-throttle-debounce-plugin/
 * 
 * Copyright (c) 2010 "Cowboy" Ben Alman
 * Dual licensed under the MIT and GPL licenses.
 * http://benalman.com/about/license/
 */
(function(b,c){var $=b.jQuery||b.Cowboy||(b.Cowboy={}),a;$.throttle=a=function(e,f,j,i){var h,d=0;if(typeof f!=="boolean"){i=j;j=f;f=c}function g(){var o=this,m=+new Date()-d,n=arguments;function l(){d=+new Date();j.apply(o,n)}function k(){h=c}if(i&&!h){l()}h&&clearTimeout(h);if(i===c&&m>e){l()}else{if(f!==true){h=setTimeout(i?k:l,i===c?e-m:e)}}}if($.guid){g.guid=j.guid=j.guid||$.guid++}return g};$.debounce=function(d,e,f){return f===c?a(d,e,false):a(d,f,e!==false)}})(this);
!function(t){var i=t(window);t.fn.visible=function(t,e,o){if(!(this.length<1)){var n=this.length>1?this.eq(0):this,s=n.get(0),a=i.width(),l=i.height(),o=o?o:"both",h=e===!0?s.offsetWidth*s.offsetHeight:!0;if("function"==typeof s.getBoundingClientRect){var c=s.getBoundingClientRect(),d=c.top>=0&&c.top<l,r=c.bottom>0&&c.bottom<=l,f=c.left>=0&&c.left<a,$=c.right>0&&c.right<=a,v=t?d||r:d&&r,u=t?f||$:f&&$;if("both"===o)return h&&v&&u;if("vertical"===o)return h&&v;if("horizontal"===o)return h&&u}else{var g=i.scrollTop(),p=g+l,m=i.scrollLeft(),C=m+a,w=n.offset(),b=w.top,y=b+n.height(),k=w.left,T=k+n.width(),z=t===!0?y:b,B=t===!0?b:y,R=t===!0?T:k,x=t===!0?k:T;if("both"===o)return!!h&&p>=B&&z>=g&&C>=x&&R>=m;if("vertical"===o)return!!h&&p>=B&&z>=g;if("horizontal"===o)return!!h&&C>=x&&R>=m}}}}(jQuery);
$(function(){function t(){b.length&&1024>=l?(b.height(h),k.height(h)):(b.css("height","100vh"),k.css("height","100vh"))}function i(t){if(y.length){var i=y.offset().top,e=i-t;0>=e?u.addClass("on"):u.removeClass("on")}if(k.length){var o=k.offset().top,n=o-t;10>=n&&u.removeClass("on")}if(T.length){var s=T.offset().top,a=s-t;0>=a?u.removeClass("on"):u.addClass("on")}}function e(t){w.each(function(){$(this).offset().top;$(this).visible()&&$(this).addClass("complete")})}function o(t){m.each(function(){var i=$(this).offset().top-t+h/2,e=$(this).attr("id");i>0&&h>i?$('a[data-name="'+e+'"]').addClass("active"):$('a[data-name="'+e+'"]').removeClass("active")})}function n(t){l>1024&&C.each(function(){var i=$(this).offset().top,e=i-t;$(this).visible(!0)?($(this).find(".videocontainer").css("display","block"),$(this).find(".videocontainer").css("transform","translate3d(0, "+-1*(e/2)+"px, 0)")):$(this).find(".videocontainer").css("display","none")})}function s(t){for(var i,e,o=t.length;0!==o;)e=Math.floor(Math.random()*o),o-=1,i=t[o],t[o]=t[e],t[e]=i;return t}function a(){var t=[0,1,2,3,4,5,6,7,8,9];t=s(t),g.each(function(i){$(this).addClass("fadein-"+t[i])})}var l=$(window).width(),h=$(window).height(),c=$(window).scrollTop(),d=$(document),r=$(window),f=$("body"),v=$("nav"),u=$("#top"),g=($("#dots"),$("a.randomfade")),p=$(".menubutton"),m=$(".screen"),C=$(".parallax"),w=$(".slidein"),b=$("#intro"),y=$("#lead"),k=($("#leadbg"),$("#contact")),T=$("#everything.white"),z=$("#main.team > div"),B=$("div.capitem");B.click(function(){$(this).hasClass("active")?($(this).removeClass("active"),$(this).find("div").slideUp()):(B.removeClass("active"),B.find("div").slideUp(),$(this).addClass("active"),$(this).find("div").slideDown())}),z.click(function(){z.removeClass("hovered"),$(this).addClass("hovered")}),$("a[href*=#]:not([href=#])").click(function(){if(location.pathname.replace(/^\//,"")==this.pathname.replace(/^\//,"")&&location.hostname==this.hostname){var t=$(this.hash);if(t=t.length?t:$("[name="+this.hash.slice(1)+"]"),t.length)return $("html,body").animate({scrollTop:t.offset().top},1e3),!1}}),i(c),n(c),o(c),e(c),t(),a(),p.click(function(){f.toggleClass("slide"),v.hasClass("active")?setTimeout(function(){v.removeClass("active")},201):v.addClass("active")}),d.on("click","body.slide #everything",function(){f.toggleClass("slide")}),d.on("click","body.slide div.screen.short",function(){f.toggleClass("slide")}),r.resize(function(){c=r.scrollTop(),l=$(window).width(),h=$(window).height(),n(c),o(c),e(c),t()}),r.scroll(function(){c=r.scrollTop(),i(c),n(c),o(c),e(c),t(),u.addClass("disabled")}),r.scroll($.debounce(500,function(){u.removeClass("disabled")})),r.load(function(){i(c),n(c),o(c),e(c),t()})});